services:
  user-service:
    build: ./s1-UserService
    ports:
      - 5000:5000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
      POSTGRE_URI: postgres://postgres:postgres@postgres:5432/postgres_ems
      JWT_SECRET: secret
    networks:
      - ecommerce-network
    depends_on:
      - postgres
    deploy:
      replicas: 1
  product-service:
    build: ./s2-ProductService
    ports:
      - 5001:5001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
      POSTGRE_URI: postgres://postgres:postgres@postgres:5432/postgres_ems
      JWT_SECRET: secret
    networks:
      - ecommerce-network
    depends_on:
      - postgres
    deploy:
      replicas: 1

  cart-service:
    build: ./s6-CartService
    ports:
      - 5002:5002
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
      POSTGRE_URI: postgres://postgres:postgres@postgres:5432/postgres_ems
      JWT_SECRET: secret
    networks:
      - ecommerce-network
    depends_on:
      - postgres
    deploy:
      replicas: 1

  order-service:
    build: ./s3-OrderService
    ports:
      - 5003:5003
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
      POSTGRE_URI: postgres://postgres:postgres@postgres:5432/postgres_ems
      JWT_SECRET: secret
    networks:
      - ecommerce-network
    depends_on:
      - postgres
    deploy:
      replicas: 1

  payment-service:
    build: ./s4-PaymentService
    ports:
      - 5004:5004
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
      POSTGRE_URI: postgres://postgres:postgres@postgres:5432/postgres_ems
      JWT_SECRET: secret
    networks:
      - ecommerce-network
    depends_on:
      - ngrok
      - postgres
    deploy:
      replicas: 1

  gateway:
    build: ./s0-Gateway
    ports:
      - "80:80"
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "gateway:80"
    environment:
      NGROK_AUTHTOKEN: 2WGHJXYorQq1tNA3u41AqtfXao7_6K59XZhC9VhW2c7BvLHqE
    ports:
      - "4040:4040" # Web UI de ngrok
    networks:
      - ecommerce-network

  front:
    build: ./front
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      # - product-service
      # - cart-service
      # - order-service
      # - payment-service
    profiles:
      - disabled

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_ems
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-network

volumes:
  pgdata:

networks:
  ecommerce-network:
    driver: bridge
