## /api/users - http://user-service:5000
## /api/products - http://product-service:5001
## /api/cart - http://shopping-cart:5002
## /api/orders - http://order-service:5003
## /api/notification - http://notification-service:5004

### Health Check
GET http://localhost:80/v1/health
Accept: application/json

### Register
POST http://localhost:80/api/users/v1/register
Content-Type: application/json

{
  "name": "Fer",
  "email": "fer@example.com",
  "password": "123456"
}

### Login
POST http://localhost:80/api/users/v1/login
Content-Type: application/json

{
  "email": "fer@example.com",
  "password": "123456"
}

### Validate 
@token = token
GET http://localhost:80/api/users/v1/validate
Authorization: Bearer {{token}}
Accept: application/json


// ****************************************************************************************

### Get All Products
GET http://localhost:80/api/products/v1/products
Accept: application/json

### Get Product By Id
GET http://localhost:80/api/products/v1/products/1
Accept: application/json

### Create Product
POST http://localhost:80/api/products/v1/product
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description 1",
  "price": 100.00,
  "stock": 10 
}


